USE ROLE ACCOUNTADMIN;
USE DATABASE ENTERPRISE_DB;
USE SCHEMA AI_SCHEMA;
USE WAREHOUSE AI_WH;

PUT file://D:\projects\snowflake-research\feedback_app.py @APP_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

CREATE OR REPLACE STREAMLIT FEEDBACK_DASHBOARD
    ROOT_LOCATION = '@ENTERPRISE_DB.AI_SCHEMA.APP_STAGE'
    MAIN_FILE = '/feedback_app.py'
    QUERY_WAREHOUSE = 'AI_WH';
